version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      $FORWARDED_ALLOW_IPS: "*"
      UVICORN_HOST: 0.0.0.0
    ports:
      - "8000:${UVICORN_PORT:-8000}"
